### ISSUE TITLE
Impact Stories_Two Battles in One Lfetime Part 1 Performance Review Lighthouse

### ISSUE THREAD

**Issue by cherylrepal** [Virtualahan/virtualahan-com#104]
[Impact Stories_Two Battles In One Lifetime (Part 1).pdf](https://github.com/Virtualahan/virtualahan-com/files/6316274/Impact.Stories_Two.Battles.In.One.Lifetime.Part.1.pdf)

**Comment by kyooreasmayk** [comment]
Consolidated (#111)
