### ISSUE TITLE
Impact Stories_Two Battles in One Lifetime Part 2 Performance Review Lighthouse

### ISSUE THREAD

**Issue by cherylrepal** [Virtualahan/virtualahan-com#105]
[Impact Stories_Two Battles In One Lifetime (Part 2).pdf](https://github.com/Virtualahan/virtualahan-com/files/6316280/Impact.Stories_Two.Battles.In.One.Lifetime.Part.2.pdf)

**Comment by kyooreasmayk** [comment]
Consolidated (#111)
