### ISSUE TITLE
Impact Stories_Virtualahan's Fathers' Month Special Performance Review Lighthouse

### ISSUE THREAD

**Issue by cherylrepal** [Virtualahan/virtualahan-com#106]
[Impact Stories_Virtualahan’s Fathers’ Month Special.pdf](https://github.com/Virtualahan/virtualahan-com/files/6316302/Impact.Stories_Virtualahan.s.Fathers.Month.Special.pdf)

**Comment by kyooreasmayk** [comment]
Consolidated (#111)
