### ISSUE TITLE
ToolTip Errors

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#120]
ToolTip for Coach Alfred and Coach Sarah were the same as Coach Mike's.

The grammar doesn't seem right as well.

![Screenshot_1](https://user-images.githubusercontent.com/81419695/115944213-000a2e80-a4e7-11eb-9590-670aede21142.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/81419695/115944224-11ebd180-a4e7-11eb-82bf-69194a91c392.jpg)

![Screenshot_3](https://user-images.githubusercontent.com/81419695/115944235-2760fb80-a4e7-11eb-8193-089a0ef99023.jpg)

**Comment by kyooreasmayk** [comment]
- [x] Update tooltip info for Mike

**Comment by kyooreasmayk** [comment]
- [x] Updated tooltip info for Coach Alfred & jael

> Coach Alfred - Alfred has over a decade of experience in the business processing outsourcing industry in different leadership roles. He specializes in strategy-making, problem-solving, and coaching.

> Coach Jael - Jael is a licensed psychometrician and a mental health & wellness advocate. With over 10 years of academic and corporate experience, she continually champions equal employment opportunities for Persons with Disabilities (PWDs). She believes that fostering diversity and inclusion in the workplace drives business transformation. Alongside her corporate career, Jael is a singer-songwriter and a sign language interpreter.

**Comment by kyooreasmayk** [comment]
Approved / Tracked v2.0.2
