### ISSUE TITLE
"Founder Spotlight: Ryan Gersava of Virtualahan" article link error

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#121]
The article "Founder Spotlight: Ryan Gersava of Virtualahan" opens an Amazon store URL.

![Media Features](https://user-images.githubusercontent.com/81419695/115945362-08b23300-a4ee-11eb-86da-5d2ec6f1fd1f.png)

![Amazon](https://user-images.githubusercontent.com/81419695/115945344-e7e9dd80-a4ed-11eb-94f3-92a53d139ac4.JPG)

**Comment by kyooreasmayk** [comment]
- [x] Update URL 
FROM:

> taste.company/social-responsibility/people/virtual-reality/

TO: 

> https://www.techshake.asia/articles/89-founder-spotlight-ryan-gersava-of-virtualahan

**Comment by kyooreasmayk** [comment]
Approved / Tracked v2.0.2
