### ISSUE TITLE
May 2019 Newsletter Broken image

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#122]
There is a broken image in May 2019 Newsletter page.

https://virtualahan.com/may-2019-newsletter/

![May 2019 Newslet](https://user-images.githubusercontent.com/81419695/115996406-b0745180-a611-11eb-9a0d-d13680086d9a.png)

**Comment by kyooreasmayk** [comment]
- [x] Update URLs | Remove 'testing' subdomain > Issue Fixed 
FROM:

> 
> ```
> <img class="alignnone wp-image-4043" src="http://testing.virtualahan.com/wp-content/uploads/2019/06/GenSan-with-Rose-and-Max-300x225.jpg" alt="" width="409" height="307" />
> 
> <img class="alignnone  wp-image-4047" src="http://testing.virtualahan.com/wp-content/uploads/2019/06/Cebu-Meet-Up-300x225.jpg" alt="" width="427" height="320" />
> 
> <div class="csColumnGap" style="margin: 0px; padding: 0px; float: left; width: 6.56%;"><img style="border: none;" src="http://testing.virtualahan.com/wp-content/plugins/advanced-wp-columns/assets/js/plugins/views/img/1x1-pixel.png" /></div>
> 
> <img class="alignnone  wp-image-4046" src="http://testing.virtualahan.com/wp-content/uploads/2019/06/At-Microsoft-300x188.jpg" alt="" width="343" height="215" />
> 
> <img class="alignnone  wp-image-4048" src="http://testing.virtualahan.com/wp-content/uploads/2019/06/TEAM-26-Graduation-Rites-300x300.jpg" alt="" width="337" height="337" />
> ```


TO:
> 
> ```
> <img class="alignnone wp-image-4043" src="http://virtualahan.com/wp-content/uploads/2019/06/GenSan-with-Rose-and-Max-300x225.jpg" alt="" width="409" height="307" />
> 
> <img class="alignnone  wp-image-4047" src="http://virtualahan.com/wp-content/uploads/2019/06/Cebu-Meet-Up-300x225.jpg" alt="" width="427" height="320" />
> 
> <div class="csColumnGap" style="margin: 0px; padding: 0px; float: left; width: 6.56%;"><img style="border: none;" src="http://virtualahan.com/wp-content/plugins/advanced-wp-columns/assets/js/plugins/views/img/1x1-pixel.png" /></div>
> 
> <img class="alignnone  wp-image-4046" src="http://virtualahan.com/wp-content/uploads/2019/06/At-Microsoft-300x188.jpg" alt="" width="343" height="215" />
> 
> <img class="alignnone  wp-image-4048" src="http://virtualahan.com/wp-content/uploads/2019/06/TEAM-26-Graduation-Rites-300x300.jpg" alt="" width="337" height="337" />
> ```

**Comment by kyooreasmayk** [comment]
Approved / Tracked v2.0.2
