### ISSUE TITLE
Impact Story broken image

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#123]
The Impact Story "The Strand of Hope" has a broken image.

![The Strand of Ho](https://user-images.githubusercontent.com/81419695/115997684-a6a11d00-a616-11eb-803d-6dd3f842b39b.png)

**Comment by kyooreasmayk** [comment]
- [x] Update URL | Remove 'testing' subdomain > Issue Fixed
FROM:

> `<img class="size-full wp-image-6321 alignleft" src="http://testing.virtualahan.com/wp-content/uploads/2021/02/23.jpg" alt="" width="275" height="206" />`

TO: 

> `<img class="size-full wp-image-6321 alignleft" src="http://virtualahan.com/wp-content/uploads/2021/02/23.jpg" alt="" width="275" height="206" />`

**Comment by kyooreasmayk** [comment]
Approved / Tracked v2.0.2
