### ISSUE TITLE
Virtualahan August Newsletter broken images

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#124]
Images in this page are broken.

https://virtualahan.com/august-newsletter/

![virtualahan-com-august-newsletter](https://user-images.githubusercontent.com/81419695/115997793-05ff2d00-a617-11eb-9bba-553d6054655f.png)

**Comment by kyooreasmayk** [comment]
- [x] Update URLs and remove 'testing' subdomain > Issue Fixed
FROM:

> ```
> <img class="size-medium wp-image-3089 alignleft" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/phildev-300x225.jpg" alt="" width="300" height="225" />
> <img class="size-medium wp-image-3092 alignleft" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/image003-300x225.jpg" alt="" width="300" height="225" />
> <img class="wp-image-3093 alignright" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/ryan-300x203.png" alt="" width="383" height="259" />
> ```

TO:
> ```
> <img class="size-medium wp-image-3089 alignleft" src="http://virtualahan.com/wp-content/uploads/2019/02/phildev-300x225.jpg" alt="" width="300" height="225" />
> <img class="size-medium wp-image-3092 alignleft" src="http://virtualahan.com/wp-content/uploads/2019/02/image003-300x225.jpg" alt="" width="300" height="225" />
> <img class="wp-image-3093 alignright" src="http://virtualahan.com/wp-content/uploads/2019/02/ryan-300x203.png" alt="" width="383" height="259" />
> ```

**Comment by kyooreasmayk** [comment]
Approved / Tracked v2.0.2
