### ISSUE TITLE
Virtualahan February Newsletter

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#125]
This page has a broken image.

https://virtualahan.com/february-2019-newsletter/

![virtualahan-com-february-2019-newsletter](https://user-images.githubusercontent.com/81419695/115998854-de5e9380-a61b-11eb-8906-268e9b44ae4e.JPG)

**Comment by kyooreasmayk** [comment]
- [x] Update URL | Remove 'testing' subdomain > Issue Fixed
FROM:

> `<img class="alignnone wp-image-3590" src="http://testing.virtualahan.com/wp-content/uploads/2019/03/VISAYAS-VISIT3-300x225.jpg" alt="" width="379" height="284" /> `

TO:

> `<img class="alignnone wp-image-3590" src="http://virtualahan.com/wp-content/uploads/2019/03/VISAYAS-VISIT3-300x225.jpg" alt="" width="379" height="284" />`

**Comment by kyooreasmayk** [comment]
Approved / Tracked v2.0.2
