### ISSUE TITLE
February 2017 content is Lorem ipsum

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#127]
The February 2017 monthly archives content uses Lorem ipsum content both for page 1 and 2.

https://virtualahan.com/2017/02/

https://virtualahan.com/2017/02/page/2/

![https-virtualahan-com-2017-02](https://user-images.githubusercontent.com/81419695/116085440-6652a500-a6d1-11eb-8a51-299d77c3a6bc.png)

![https-virtualahan-com-2017-02-page-2](https://user-images.githubusercontent.com/81419695/116085456-6a7ec280-a6d1-11eb-8348-005c3e9d64cd.png)

**Comment by kyooreasmayk** [comment]
- [x] Delete posts: (test posts that were not deleted)
  - https://virtualahan.com/neque-adipiscing-an-cursus/
  - https://virtualahan.com/litora-torqent-per-conubia/
  - https://virtualahan.com/praesent-libro-se-cursus-ante/
  - https://virtualahan.com/metus-vitae-pharetra-auctor/
  - https://virtualahan.com/interdum-magna-augue-eget/
  - https://virtualahan.com/torquent-per-conubia-nostra/

**Comment by kyooreasmayk** [comment]
- [x] Release - v2.0.3
