### ISSUE TITLE
July newsletter broken images

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#128]
https://virtualahan.com/july-newsletter/

![July Newsletter ](https://user-images.githubusercontent.com/81419695/116086107-0c061400-a6d2-11eb-896e-2cd4e99ab4aa.png)

**Comment by kyooreasmayk** [comment]
- [x] Update image URLs > Remove 'testing' in image urls

> ` <img class="alignnone wp-image-3150" src="http://testing.virtualahan.com/wp-content/uploads/2018/07/july1-300x187.jpg" alt="" width="414" height="258" />`
> 
> `<img class="wp-image-3149 alignright" src="http://testing.virtualahan.com/wp-content/uploads/2018/07/july2-300x201.jpg" alt="" width="434" height="291" />`
> 
> `<img class="size-medium wp-image-3151 alignleft" src="http://testing.virtualahan.com/wp-content/uploads/2018/07/july3-300x187.jpg" alt="" width="300" height="187" />`
> 
> `<img class="size-medium wp-image-3075 alignleft" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/radio-300x221.jpg" alt="" width="300" height="221" />`

**Comment by kyooreasmayk** [comment]
- [x] Release - v2.0.3
