### ISSUE TITLE
August Newsletter vertical line spacing

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#129]
Please adjust the line spacing between the last line of the paragraph and the succeeding subheading.

https://virtualahan.com/august-newsletter/

![https-virtualahan-com-august-newsletter](https://user-images.githubusercontent.com/81419695/116104312-ec2b1c00-a6e2-11eb-97ce-7ff4b84c20ae.png)

**Comment by kyooreasmayk** [comment]
- [x] Add line breaks every after subheading title

**Comment by kyooreasmayk** [comment]
- [x] Release - v2.0.3
