### ISSUE TITLE
November newsletter vertical line spacing

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#130]
Please adjust the line spacing between the last line of the paragraph and the succeeding subheading.

https://virtualahan.com/november-newsletter-2/

![https-virtualahan-com-november-newsletter-2](https://user-images.githubusercontent.com/81419695/116221651-63fb5400-a780-11eb-9eac-2ca36232aa5c.png)

**Comment by kyooreasmayk** [comment]
- [x] Add line breaks every after subheading title 
![image](https://user-images.githubusercontent.com/16027530/116679033-9e612d00-a9dc-11eb-8bb7-6f71b53c461d.png)

**Comment by kyooreasmayk** [comment]
- [x] Release - v2.0.3
