### ISSUE TITLE
October newsletter broken images

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#131]
https://virtualahan.com/october-newsletter/

![https-virtualahan-com-october-newsletter](https://user-images.githubusercontent.com/81419695/116222030-c5232780-a780-11eb-94ba-32cc3dcaa3db.png)

**Comment by kyooreasmayk** [comment]
- [x] Update image URLs > Remove 'testing' in image URL

> `<img class="size-medium wp-image-3108 alignleft" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/11-300x300.jpg" alt="" width="300" height="300" />`
> 
> `<img class="size-medium wp-image-3115 alignright" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/rose-300x300.jpg" alt="" width="300" height="300" />`
> 
> `<img class="size-medium wp-image-3114 alignleft" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/jha-240x300.jpg" alt="" width="240" height="300" />`

**Comment by kyooreasmayk** [comment]
- [x] Release - v2.0.3
