### ISSUE TITLE
September newsletter broken images

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#132]
https://virtualahan.com/september-newsletter/

![https-virtualahan-com-september-newsletter](https://user-images.githubusercontent.com/81419695/116223879-91490180-a782-11eb-93c3-416d9d59f959.png)

**Comment by kyooreasmayk** [comment]
- [x] Update image URLs > Remove 'testing' in image URL

> ` <img class="wp-image-3102 alignleft" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/felipe-300x203.jpg" alt="" width="398" height="269" />`
> `<img class="wp-image-3103 alignright" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/vhanaccenture-300x225.jpg" alt="" width="403" height="302" />`
> `<img class="size-medium wp-image-3104 alignleft" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/2-300x298.png" alt="" width="300" height="298" />`
> `<img class="size-medium wp-image-3105 alignleft" src="http://testing.virtualahan.com/wp-content/uploads/2019/02/obesity-300x300.png" alt="" width="300" height="300" />`
