### ISSUE TITLE
February newsletter vertical line spacing

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#133]
Please adjust the line spacing between the last line of the paragraph and the succeeding subheading.

https://virtualahan.com/february-2019-newsletter

![httpsvirtualahan comfebruary-2019-newsletter](https://user-images.githubusercontent.com/81419695/116233932-81371f00-a78e-11eb-8995-113c511d1b48.png)

**Comment by kyooreasmayk** [comment]
- [x] Add line break before every subheading title
![image](https://user-images.githubusercontent.com/16027530/116677758-2b0aeb80-a9db-11eb-8ab6-272cdbf7fc94.png)

**Comment by kyooreasmayk** [comment]
- [x] Release - v2.0.3
