### ISSUE TITLE
Enroll Now page missing background

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#137]
https://virtualahan.com/enrollnow/

Background picture missing.

![Enroll Now - Vir](https://user-images.githubusercontent.com/81419695/116262958-8eaed200-a7ab-11eb-8f22-c2e802e1bb35.png)

It should be like this.

![234](https://user-images.githubusercontent.com/81419695/116262980-94a4b300-a7ab-11eb-804a-9936c380347e.JPG)

**Comment by kyooreasmayk** [comment]
- [x] Add image again
  - image: http://virtualahan.com/wp-content/uploads/2020/01/group-shot.jpg
![image](https://user-images.githubusercontent.com/16027530/116674330-16c4ef80-a9d7-11eb-81e9-a2ba89673db0.png)

**Comment by kyooreasmayk** [comment]
- [x] Release - v2.0.3
