### ISSUE TITLE
"Send Message" button color

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#138]
Send message button in the Contact Us form should be white.

![546](https://user-images.githubusercontent.com/81419695/116269733-09c6b700-a7b1-11eb-8898-81f7ce9dc037.JPG)

**Comment by kyooreasmayk** [comment]
- This is intended for accessibility purposes. 
- Reference: [Color Paletter version 3](https://github.com/Virtualahan/virtualahan-com/blob/5fba89f737ad009726f040cde09990803422f79b/Virtualahan.com%20Color%20Palette%20(v3).png)
