### ISSUE TITLE
Footer background image

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#139]
Missing background image in the footer

![Bg image footer](https://user-images.githubusercontent.com/81419695/116270046-54e0ca00-a7b1-11eb-990a-ee6ca4514aad.JPG)

**Comment by kyooreasmayk** [comment]
- [x] Added image again
  - https://virtualahan.com/wp-admin/post.php?post=4482&action=elementor#
  - image: "books-business-computer-connection-459654.jpg"

**Comment by kyooreasmayk** [comment]
- [x] Release - v2.0.3
