### ISSUE TITLE
Site is running an insecure version of PHP (7.1.33), which should be updated to PHP 7.4+

### ISSUE THREAD

**Issue by kyooreasmayk** [Virtualahan/virtualahan-com#31]
**Describe the bug**
Site is running an insecure version of PHP (7.1.33).

**Screenshots**
![image](https://user-images.githubusercontent.com/16027530/113538629-4d912b00-960e-11eb-8388-c3042bf0bd26.png)

**Comment by CMayk** [comment]
- Set up Azure App Service Plan:
  - S1
  - 100 total ACU
  - 1.75 GB memory
  - A-Series compute equivalent
  - Location: East Asia
- Add App > URL: https://itp006-virtualahan-com.azurewebsites.net
- Migrate wordpress website > care of Ronniel Javier

**Comment by kyooreasmayk** [comment]
Migration to Azure VM will fix this #32
