### ISSUE TITLE
Impact Stories_A beautiful disaster Part 1 Performance Review Lighthouse

### ISSUE THREAD

**Issue by cherylrepal** [Virtualahan/virtualahan-com#68]
[Impact Stories_A Beautiful Disaster (Part 1).pdf](https://github.com/Virtualahan/virtualahan-com/files/6315862/Impact.Stories_A.Beautiful.Disaster.Part.1.pdf)

**Comment by kyooreasmayk** [comment]
Consolidated (#111)
