### ISSUE TITLE
Impact Stories_A Beautiful Disaster Part 2 Performance Review Lighthouse

### ISSUE THREAD

**Issue by cherylrepal** [Virtualahan/virtualahan-com#69]
[Impact Stories_A Beautiful Disaster (Part 2).pdf](https://github.com/Virtualahan/virtualahan-com/files/6315869/Impact.Stories_A.Beautiful.Disaster.Part.2.pdf)

**Comment by kyooreasmayk** [comment]
Consolidated (#111)
