### ISSUE TITLE
Homepage Performance Review (Lighthouse)

### ISSUE THREAD

**Issue by cherylrepal** [Virtualahan/virtualahan-com#70]
![image](https://user-images.githubusercontent.com/77714516/114827837-c016bd80-9dfb-11eb-85a1-b10e9c71b84e.png)
![image](https://user-images.githubusercontent.com/77714516/114827910-d755ab00-9dfb-11eb-9a54-4217847892aa.png)
![image](https://user-images.githubusercontent.com/77714516/114827956-e4729a00-9dfb-11eb-9df6-b79a44e3668f.png)
![image](https://user-images.githubusercontent.com/77714516/114828016-f81e0080-9dfb-11eb-84e6-0fa576ecd6b0.png)
![image](https://user-images.githubusercontent.com/77714516/114828984-1b957b00-9dfd-11eb-8b27-362c467c1235.png)
![image](https://user-images.githubusercontent.com/77714516/114829021-2b14c400-9dfd-11eb-9bad-993541bbb739.png)
![image](https://user-images.githubusercontent.com/77714516/114829196-5bf4f900-9dfd-11eb-8f94-dfe20bb857cf.png)
![image](https://user-images.githubusercontent.com/77714516/114829278-74651380-9dfd-11eb-83da-474217896b23.png)
![image](https://user-images.githubusercontent.com/77714516/114829438-a7a7a280-9dfd-11eb-9012-3899e0940856.png)
![image](https://user-images.githubusercontent.com/77714516/114829513-c0b05380-9dfd-11eb-9e44-d6cb3ad3b531.png)
![image](https://user-images.githubusercontent.com/77714516/114829663-f0f7f200-9dfd-11eb-84dc-c67c32f42ff6.png)

**Comment by kyooreasmayk** [comment]
Consolidated (#111)
