### ISSUE TITLE
Impact Stories_Dare to Live Performance Review Lighthouse

### ISSUE THREAD

**Issue by cherylrepal** [Virtualahan/virtualahan-com#78]
[Impact Stories_Dare To Live.pdf](https://github.com/Virtualahan/virtualahan-com/files/6315995/Impact.Stories_Dare.To.Live.pdf)

**Comment by cherylrepal** [comment]
[Impact Stories_Changed Vision.pdf](https://github.com/Virtualahan/virtualahan-com/files/6315964/Impact.Stories_Changed.Vision.pdf)

**Comment by kyooreasmayk** [comment]
Consolidated (#111)
