### ISSUE TITLE
Missing first level heading

### ISSUE THREAD

**Issue by cynthiaguilas** [Virtualahan/virtualahan-com#8]
A page does not have a first level heading.

![Home_H1](https://user-images.githubusercontent.com/81419695/113466673-3ae0ef80-9470-11eb-8252-74e10b28b0d1.JPG)

**Comment by kyooreasmayk** [comment]
- [x] Update "Business Value + Social Impact" from H2 to H1

**Comment by kyooreasmayk** [comment]
Tracked: v2.1.0
