### ISSUE TITLE
Impact Stories_In Pursuit of A Normal Life Performance Review Lighthouse

### ISSUE THREAD

**Issue by cherylrepal** [Virtualahan/virtualahan-com#88]
[Impact Stories_In Pursuit Of “A Normal” Life.pdf](https://github.com/Virtualahan/virtualahan-com/files/6316133/Impact.Stories_In.Pursuit.Of.A.Normal.Life.pdf)

**Comment by kyooreasmayk** [comment]
Consolidated (#111)
