### ISSUE TITLE
Impact Stories_Living with an Incurable Disease Performance Review Lighthouse

### ISSUE THREAD

**Issue by cherylrepal** [Virtualahan/virtualahan-com#91]
[Impact Stories_Living With An Incurable Disease (Part I).pdf](https://github.com/Virtualahan/virtualahan-com/files/6316158/Impact.Stories_Living.With.An.Incurable.Disease.Part.I.pdf)

**Comment by kyooreasmayk** [comment]
Consolidated (#111)
