### ISSUE TITLE
Impact Stories_Living with Incurable Diseases Part 2 Performance Review Lighthouse

### ISSUE THREAD

**Issue by cherylrepal** [Virtualahan/virtualahan-com#92]
[Impact Stories_Living With An Incurable Disease (Part II).pdf](https://github.com/Virtualahan/virtualahan-com/files/6316169/Impact.Stories_Living.With.An.Incurable.Disease.Part.II.pdf)

**Comment by kyooreasmayk** [comment]
Consolidated (#111)
